### ISSUE TITLE
expo start error 

### ISSUE THREAD

**Issue by toutpuissantged** [llRizvanll/CliqApp#10]
Did you know: You can turn off automatic updates under Devices in the footer?
Unable to resolve module 'screens/.js'
  Evaluating screens/.js
  Evaluating navigations/HomeNavigator.tsx.js
  Evaluating navigations/AppNavigator.tsx.js
  Evaluating App.tsx.js
  Loading App.tsx
Error: Unable to resolve module 'screens/.js'
    at Object.eval (screens/.js:1:1

    at eval (screens/.js

    at eval (screens/.js

    at eval (<anonymous>)
    at [snack internals]
    at Object.a ([snack internals]
    at e.evaluate ([snack internals]
    at Ze ([snack internals]
    at [snack internals]
    at https://snack-web-player.s3.us-west-1.amazonaws.com/v2/42/static/js/app.056cc19a.chunk.js:1:14427

**Comment by ShubhamAggarwal2402** [comment]
Can you please share your App.tsx and screen.js file??
